### ISSUE TITLE
write password without windows gui

### ISSUE THREAD

**Issue by coolegoschin** [gerardog/gsudo#118] opened 2021-11-10 20:48 UTC
Please add the ability to enter a password via cmd. This option is required for use on a server without a gui.
Enter the password in the same way as in linux sudo.

gsudo -s cmd.exe
password: (local admin password)

**Comment by gerardog** [comment] 2021-11-29 01:18
This looks like a dupe of #28

What do you mean by server without gui? Windows Server Core has UAC disabled, so everything runs elevated AFAIK.
How do you connect to a server without a GUI? Do you SSH? Can´t SSH spawn to an elevated CMD instead?

The UAC popup is required to launch the elevated gsudo helper. Unless you install gsudo as a service. 
Are you willing to install gsudo as a service? First it would require at least one UAC consent...

Alternative you can start an elevated cache session, by opening a cmd as admin and then creating a scheduled task:
```
powershell -c "$Sta = New-ScheduledTaskAction -Execute 'C:\path to gsudo\gsudo.exe' -Argument 'cache on -p 0' ; $Stset= New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries ; Register-ScheduledTask GsudoCache -Action $Sta -RunLevel Highest"
```

Then start the cache with no UAC consent: 
`SCHTASKS /Run /TN "GsudoCache"`

Run the elevated command 
`gsudo MyAppConsoleApp`

**Comment by gerardog** [comment] 2022-02-27 22:18
After giving a second thought on this. There is a reason why windows uses a separate desktop on the UAC popup. To ensure no other app can capture the keystrokes of the elevated password. It wouldnt be a good idea to implement this on gsudo. You may better better disable UAC altogether on your server. Sorry

**Closed by gerardog** 2022-02-27 22:18 UTC
