### ISSUE TITLE
Issue: Can't run a function from PowerShell profile with gsudo

### ISSUE THREAD

**Issue by devmcp** [gerardog/gsudo#130] opened 2022-03-18 10:53 UTC
## Issue Description

I have a function defined in `$PROFILE.AllUsersAllHosts` called e.g. `test_function`.

I can run:

```
gsudo
```

to get the elevated shell, then:

```
test_function
```

successfully, but if I try:

```
gsudo test_function
```

this fails with:

```
test_function: The term 'test_function' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
 
Is this expected behaviour?

Many thanks!

## Context:
 - Windows version: 10, Version 21H2
 - gsudo version:      1.1.1

**Comment by gerardog** [comment] 2022-03-19 01:46
Yes, this is by design.
Elevated code runs in a new powershell process. And I decided it should not load the profile (`pwsh -noprofile`) because it may take too long to load (I.E. oh-my-posh initialization, etc, etc... takes almost 2 seconds on my setup).

Nonetheless, this behaviour was reported as an issue more than once already, so... 
I should add a configuration for those of you who want to load the profile on each elevation.

**Comment by gerardog** [comment] 2022-03-23 14:06
Why I had chosen to not load the profile by default? 
- Loading it may be slow.
- Some stuff may be not needed on non interactive sessions, like gsudo elevations. For example, omitting loading Oh-My-Posh in this context makes sense.
- If the profile writes to the Console, that would break the user workflow, for example:
```
C:\> pwsh
PowerShell 7.2.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

My custom profile was loaded successfully!
PS C:\> gsudo echo (1+1)
My custom profile was loaded successfully!
2
PS C:\>
```

**NEW**: Option to load your profile:

Using `gsudo`:
 - `PS C:\> gsudo --loadProfile echo (1+1)`
 - Set as a permanent setting with `gsudo config PowerShellLoadProfile true`

Using `Invoke-gsudo`:
 - `PS C:\> Invoke-Gsudo { echo (1+1) } -LoadProfile`
 - Set as a permanent setting by running `$gsudoLoadProfile=$true` or add that line to your `$PROFILE` after `Import-Module C:\FullPathTo\gsudoModule.psd1`

This will be released in `v1.2`. You can give it a try (and help testing it, please!) if you manually install the [latest build](https://ci.appveyor.com/project/gerardog/gsudo/builds/42991774/artifacts)

**Comment by gerardog** [comment] 2022-03-25 13:06
Released in v1.2.0, please give it a try and let me know. Thanks

**Closed by gerardog** 2022-03-25 13:06 UTC

**Comment by devmcp** [comment] 2022-03-25 19:12
This looks fantastic. Thanks!

I’ve been away so not tried it yet but will do so on Monday and will report back

**Comment by devmcp** [comment] 2022-03-28 16:20
I enabled permanently with `gsudo config PowerShellLoadProfile true` and it works just as expected. Many thanks for implementing this! It's a great little tool 🙂
