### ISSUE TITLE
Powershell output width differs when using piped mode.

### ISSUE THREAD

**Issue by lazna** [gerardog/gsudo#86] opened 2021-05-09 08:57 UTC
As writen in gsudo documentation, gsudo catch powershell textual outputs and print it into console. But are you aware of this:

`Standard PowerShell output will trim/wrap output lines to match the width of the parent console window -1` https://ss64.com/ps/write-host.html

It does not make any problems for me until now, just FYI.

**Comment by gerardog** [comment] 2021-05-22 15:13
Is there any specific issue that can be addressed or else would be fine If I close this issue?

**Comment by JohnLGalt** [comment] 2021-05-22 16:44
From me?  Not thus far.  It works like a champ.

**Comment by gerardog** [comment] 2021-08-06 11:36
> Standard PowerShell output will trim/wrap output lines to match the width of the parent console window -1

I was able to reproduce a problem related to this, in piped mode (--piped) or SecurityEnforceUacIsolation=true.

The piped mode is not relevant per se, it may be removed at some point in the future. The thing is currently SecurityEnforceUacIsolation uses piped (for elevation in current console).

![image](https://user-images.githubusercontent.com/3901474/128448190-bc161f0d-5066-4bac-a17d-ecdcfd8067c0.png)

**Comment by gerardog** [comment] 2022-03-12 03:54
I am closing this one as `known issue`, because I seriously doubt there is a way to fix it (and I've tried), plus this is a very marginal scenario given that only piped mode is affected, and the nature of piping a process means that there is no console in the first place. Also, this won't affect gsudo users unless they specifically force piped mode.
Still, thanks for reporting! This feedback improved my test suite.

**Closed by gerardog** 2022-03-12 03:54 UTC
