### ISSUE TITLE
Issue: gsudo locks up when trying to use Chocolatey within MSYS2 or Cygwin environments

### ISSUE THREAD

**Issue by koitsu** [gerardog/gsudo#263] opened 2023-05-13 00:40 UTC
## Issue Description
gsudo locks up when trying to launch Chocolatey within MSYS2 or Cygwin environments.

Process cannot be killed with Ctrl-C, Ctrl-Z, or any other means.  Underlying MSYS2 terminal or Cygwin terminal must be terminated.

I have tried using `gsudo --debug` which provides some additional information, but does not tell me what the root of the problem is.  Instead, the debug window appears, and after 15 seconds the debug window disappears while the gsudo process continues to run (in MSYS2 environment) doing absolutely nothing.  See screenshots.

## Steps to Reproduce
`gsudo choco uninstall some-package`

## Screenshots

![Untitled](https://github.com/gerardog/gsudo/assets/8430773/944bc6b1-ee4c-4d43-9b61-f08f270a8b92)

## Context:
  - Windows version: Win10 22H2 (OS Build 19045.2846) - English
  - gsudo version: gsudo v2.0.9 (Branch.tags-v2.0.9.Sha.6a6b1a4a9e062e370c230426abfff52580cf1d8f)

**Comment by koitsu** [comment] 2023-05-13 10:17
Root cause for this relates to CIFS/SMB network drive mappings on Windows 10 behaving different than on Windows 7.

The commands in my screenshot were leveraging files/things in my Q: drive, which is a network-mapped drive done at user log-on time.  On Windows 10, unlike Windows 7, when a user session is elevated to Administrator -- or even when something like Command Prompt is launched as Administrator (without gsudo) -- network-mapped drives (done by a user) no longer appear for Administrator.

The registry flag [EnableLinkedConnections](https://learn.microsoft.com/en-US/troubleshoot/windows-client/networking/mapped-drives-not-available-from-elevated-command) controls this behaviour, where a value of 1 will allow such drive mappings to be retained ("linked") between the user session and the Administrator session (i.e. drives appear when doing things as Administrator).  [This Serverfault link](https://serverfault.com/questions/780639/enablelinkedconnections-isnt-working-on-some-windows-10-machines/) was also helpful.  You can refer to https://github.com/chocolatey/choco/issues/3156#issuecomment-1546609256 and https://github.com/chocolatey/choco/issues/3156#issuecomment-1546611076 for some details.


That said:  **I was not able to reproduce this problem under Command Prompt (when EnableLinkedConnections=0).**

The way this manifests under MSYS2 or Cygwin (re: gsudo sitting there doing nothing forever) is definitely an uncomfortable bug, but where the "hanging indefinitely" problem lies (re: gsudo vs. MSYS2 vs. Cygwin) is not something I'm able to narrow down.

Feel free to close this issue/ticket if you wish, as my work is unblocked with EnableLinkedConnections=1.

**Comment by gerardog** [comment] 2023-05-14 18:00
Hi! thanks for the detailed ticket,

There is a section in the [project readme](https://github.com/gerardog/gsudo#known-issues) that explains this: 

> ## Known issues
> 
> - The elevated instances do not have access to the network shares connected on the non-elevated space. This is not a `gsudo` issue but how Windows works. Use `--copyNS` to replicate Network Shares into the elevated session, but this is not bi-directional and is interactive (may prompt for user/password).
> 
> - `gsudo.exe` can be placed on a network share and invoked as `\\server\share\gsudo {command}` but doesn't work if your **current** folder is a network drive. For example do not map `\\server\share\` to `Z:` and then `Z:\>gsudo do-something`.

In a nutshell, windows intentionally isolates elevated and non-elevated worlds, and part of that is that network shares on both realms are independent. This limits gsudo to be invoked from a network mapped *drive* (like z:) because after elevation `z:` is not there anymore, (and some older gsudo versions even thrown a BSOD). 

There is the [`--copyns`](https://github.com/gerardog/gsudo#usage) workaround. It's not a robust solution at all but may have helped at least a little bit. I wonder if you have tried it. 

Using [EnableLinkedConnections](https://learn.microsoft.com/en-US/troubleshoot/windows-client/networking/mapped-drives-not-available-from-elevated-command) totally solves the issue because now elevated or not, you are using one single set of network connections. This eliminates the problem, by disabling an OS isolation.

I hope the information provided helps clarify the root cause of the issue and the limitations imposed by the Windows operating system regarding network shares in elevated and non-elevated contexts. 

I'm closing the issue because at this time I can't identify other actionable item or thing to improve. If you have any further questions or need additional assistance, please don't hesitate to ask.

**Closed by gerardog** 2023-05-14 18:00 UTC
