### ISSUE TITLE
gsudo change theme settings

### ISSUE THREAD

**Issue by ShadowNev** [gerardog/gsudo#51] opened 2020-07-31 11:09 UTC
Hi
is there any way do not change color and background of console when using gsudo?
![image](https://user-images.githubusercontent.com/42059626/89029527-54f18d80-d337-11ea-8e34-797dfb4f5c8d.png)

**Comment by gerardog** [comment] 2020-07-31 15:59
Looks like the elevated prompt is setting the red pound (#) and then failing to restore your green color... 
You can fetch the configured "elevated CMD prompt" with `gsudo config Prompt`.

The default one is "$p$e[1;31;40m# $e[0;37;40m" where 
 - `$p` means show your current directory
 - `$e[1;31;40m` means 'set bright mode (="1;") red color (="31") '
 - `# ` pound + space
 - `$e[0;37;40m` means 'restore normal white color' which was intended to return the default color, normally white. Clearly I wasn't seeing green as an option there.

Try: 
 - `gsudo config Prompt "$P# "` will keep the prompt green, but the red pound will be green too. (restart gsudo to take efect)
or 
 - `gsudo config Prompt "$p$e[1;31;40m# $e[1;32;40m"` will keep the red pound, and the rest of the console will be bright green: Not sure the ANSI bright green (1;31;) is your exact console green color, but close enough maybe? ...
or
- use the new 'Windows Terminal' where you wont have this issue: There you can redefine ansi colors. For example `"foreground" : "#aaCC22"` will redefine the white color to that RGB code, making the original white ("$e[0;37;40m") restore the original console color.
or, WAIT...
- Are you using the default windows console? of so: In my test I was able to reproduce your problem when I chose different colors, like these:
![image](https://user-images.githubusercontent.com/3901474/89052745-8add4480-d32c-11ea-8801-9959255d9581.png)
but it worked fine without changing `gsudo config` when done via this other tab instead:
![image](https://user-images.githubusercontent.com/3901474/89053030-fc1cf780-d32c-11ea-98c0-eebbe231f57a.png)
(dont forget to uncheck the first tab "Use separate color")

Let me know if this solves your problem. Thanks!

**Comment by ShadowNev** [comment] 2020-08-03 07:02
Window Terminal Preview
![image](https://user-images.githubusercontent.com/42059626/89154871-68d40400-d570-11ea-8f80-8000acbd90a2.png)

**Comment by ShadowNev** [comment] 2020-08-03 07:05
cmd
![image](https://user-images.githubusercontent.com/42059626/89155052-c49e8d00-d570-11ea-81aa-14f944aaf1d7.png)
![image](https://user-images.githubusercontent.com/42059626/89155075-d1bb7c00-d570-11ea-878c-edb1db257e50.png)

**Comment by ShadowNev** [comment] 2020-08-03 07:13
Windows Terminal - PowerShell
![image](https://user-images.githubusercontent.com/42059626/89155630-e0eef980-d571-11ea-94e0-d6070d131b43.png)
looks like correctly but without #

**Comment by ShadowNev** [comment] 2020-08-03 07:17
Mostly I interested in Windows Terminal
Just provided cmd.exe screen to simplify investigation ))) 
but it do not work in it too
![image](https://user-images.githubusercontent.com/42059626/89155986-99b53880-d572-11ea-9b9d-75b750b11277.png)

**Comment by gerardog** [comment] 2020-08-03 13:26
How did you setup your green font color in the first place in Windows Terminal and in Cmd?

**Comment by gerardog** [comment] 2020-08-03 14:20
PowerShell is not impacted by the `Prompt` config. In Cmd you need to restart gsudo after changing the config.

Let's start over.
Do `gsudo config Prompt --reset` to revert gsudo to the default state.
Go to WT, reset your config and ensure your prompt is no longer green.
Then add this setting:
`"foreground" : "#00FF00"`
Then you should have a working green console on WT. Now lets see how gsudo works:

On powershell, gsudo does not change the prompt at all. If you want to see an indicator that you are admin or elevated follow [this steps](https://www.hanselman.com/blog/HowToMakeAPrettyPromptInWindowsTerminalWithPowerlineNerdFontsCascadiaCodeWSLAndOhmyposh.aspx).

Example Pwsh Core (PowerShell > 6.x ) with oh-my-posh prompt installed:
![image](https://user-images.githubusercontent.com/3901474/89192391-b190ba80-d57a-11ea-80ef-fb5962f011ec.png)

Vanilla Windows PowerShell (i.e. Powershell 5.x):
![image](https://user-images.githubusercontent.com/3901474/89190730-3fb77180-d578-11ea-9929-9d44e02541b9.png)

Note I havent setup oh-my-posh on Windows PowerShell, so it's all green. Again, gsudo does not change PowerShell prompt. Do that on your own with oh-my-posh.

And CMD + WindowsTerminal:
![image](https://user-images.githubusercontent.com/3901474/89191420-4692b400-d579-11ea-865a-e4174399c356.png)
It just works out of the box.

Looks like there is something wrong with whatever you did to set the green color in the first place and then got mixed up with all the possibilities.

On regular Cmd if you do not check this option:
![image](https://user-images.githubusercontent.com/3901474/89192652-2bc13f00-d57b-11ea-816f-96d75f2a9a0c.png)"
also works out of the box 
![image](https://user-images.githubusercontent.com/3901474/89192576-0fbd9d80-d57b-11ea-82b8-0c3225e5e4b4.png)

**Comment by ShadowNev** [comment] 2020-08-03 14:43
step by step:
> Do gsudo config Prompt --reset to revert gsudo to the default state.
> Go to WT, reset your config and ensure your prompt is no longer green.
> Then add this setting:
> "foreground" : "#00FF00"
> Then you should have a working green console on WT. Now lets see how gsudo works:
and still have issue 
![image](https://user-images.githubusercontent.com/42059626/89194926-b4a69d80-d5b0-11ea-9bfd-3bed79b24500.png)

**Comment by ShadowNev** [comment] 2020-08-03 14:46
when I using Theme Cobalt2
`            "colorScheme": "Cobalt2",`
you can see background color is affected too
![image](https://user-images.githubusercontent.com/42059626/89195309-457d7900-d5b1-11ea-86c7-ce85e441a90b.png)

**Comment by ShadowNev** [comment] 2020-08-03 14:51
for cmd.exe I'm not using separate foreground and box unticked.
my current cosole settings are:
`REGEDIT4

[-HKEY_CURRENT_USER\Console]

[HKEY_CURRENT_USER\Console]
"ColorTable00"=dword:00000000
"ColorTable01"=dword:00800000
"ColorTable02"=dword:00008000
"ColorTable03"=dword:00808000
"ColorTable04"=dword:00000080
"ColorTable05"=dword:00800080
"ColorTable06"=dword:00008080
"ColorTable07"=dword:00c0c0c0
"ColorTable08"=dword:00808080
"ColorTable09"=dword:00ff0000
"ColorTable10"=dword:0000ff00
"ColorTable11"=dword:00ffff00
"ColorTable12"=dword:000000ff
"ColorTable13"=dword:00ff00ff
"ColorTable14"=dword:0000ffff
"ColorTable15"=dword:00ffffff
"CursorSize"=dword:00000019
"EnableColorSelection"=dword:00000000
"ExtendedEditKey"=dword:00000000
"ExtendedEditKeyCustom"=dword:00000000
"FontFamily"=dword:00000036
"FontSize"=dword:000c0000
"FontWeight"=dword:00000190
"FullScreen"=dword:00000000
"HistoryBufferSize"=dword:00000032
"HistoryNoDup"=dword:00000000
"InsertMode"=dword:00000001
"LoadConIme"=dword:00000001
"NumberOfHistoryBuffers"=dword:00000004
"PopupColors"=dword:000000f5
"QuickEdit"=dword:00000000
"ScreenBufferSize"=dword:012c0050
"ScreenColors"=dword:0000000a
"TrimLeadingZeros"=dword:00000000
"WindowSize"=dword:00290050
"WordDelimiters"=dword:00000000
"CurrentPage"=dword:00000003
"FaceName"="Lucida Console"
"ForceV2"=dword:00000001
`

**Comment by ShadowNev** [comment] 2020-08-03 15:25
ty
I found solution
`gsudo config Prompt "$p$e[1;31m#$e[0m "`
you sholud change `$e[0m ` it's reset console to default 

with my Prompt config it now working as expected everywhere

**Comment by gerardog** [comment] 2020-08-03 15:50
LOL, I can't reproduce it even with Cobalt2. (Cobalt2 does not have green foreground btw so Im still confused about your screenshots).
But, you are right and "$e[0m" appears to be semantically correct, so I will test it and push it. 
Thanks!

**Comment by adam-grant-hendry** [comment] 2020-11-27 22:37
Still not fixed on Release v0.7.2

**Comment by adam-grant-hendry** [comment] 2020-11-27 22:43
I want the option to not have a red "#" symbol, but it seems to still be here:

![image](https://user-images.githubusercontent.com/59346180/100487706-efcc5f80-30be-11eb-9779-43a8000bbf98.png)

**Comment by adam-grant-hendry** [comment] 2020-11-27 22:53
Wouldn't the correct fix simply be setting it back to `$p$g`? Elevated command prompts already show "Administrator: Command Prompt" in the title bar, so there's no need to change the prompt.

```
public static RegistrySetting<string> Prompt { get; set; }
    = new RegistrySetting<string>(nameof(Prompt), "$p$e[1;31;40m# $g", (s) => s);
```

**Comment by davidjade** [comment] 2020-11-27 22:57
> Elevated command prompts already show "Administrator: Command Prompt" in the title bar, so there's no need to change the prompt.

I for one, like the red # when elevated (and I wish it carried over to PS too).

**Comment by adam-grant-hendry** [comment] 2020-11-28 04:45
Then you should tell the user that you are going to change the default behavior. Otherwise, they will think it is an error.

This is much worse because they will think something is wrong with the program as opposed to the fact that the author has chosen to change a default behavior.

**Comment by adam-grant-hendry** [comment] 2020-11-28 04:46
If this were not true, it would not have been submitted as an issue to the repo nor attempted to have been changed in the last update

**Comment by gerardog** [comment] 2020-11-28 07:35
Hi all!

> If this were not true, it would not have been submitted as an issue to the repo nor attempted to have been changed in the last update

This issue as original posted was not requesting to remove the pound, but about gsudo breaking the foreground console color for everything else, when the user changed ConHost color scheme in a particular way. The fix included in v0.7.2 was a bad fix because the background color was still being screwed under some circunstances.

Before v0.7.2: 
![image](https://user-images.githubusercontent.com/3901474/100496085-f21ad200-312f-11eb-85d6-aef0108a7e87.png)

Actual v0.7.2:
![image](https://user-images.githubusercontent.com/3901474/100496109-402fd580-3130-11eb-9781-567857343706.png)

Intended: (next release)
![image](https://user-images.githubusercontent.com/3901474/100496125-69e8fc80-3130-11eb-94ce-f379088cb50c.png)

> Then you should tell the user that you are going to change the default behavior. Otherwise, they will think it is an error.

`gsudo` mimics Unix sudo, that is where the `#` sign comes from. It is a "default behaviour", at least on Unix sudo. The red color was just my idea. I imagined not everyone would like it, so you can change the configuration with `gsudo config`. I should have documented this better, but the `readme` was too long. 

You can run `gsudo config prompt "$p$e[1;31m# $e[0m"` (and then `gsudo`) to test the future default setting. Again, my intent is to have a red sharp, with no background color change. Please let me know if it doesn't work that way for you.

If you don't want the red color but you still want the pound, run: `gsudo config prompt "$p# "`
If you don't want gsudo to change the prompt at all run: `gsudo config prompt "$p$g"`

For @davidjade that likes it on PowerShell as well: The thing is PowerShell prompt is harder to configure, usually involves a defining a function in the `$PROFILE` script. Is very common for users to overwrite it, and gsudo would certainly break that customization.

But luckily the most used Pwsh customizations are using `oh-my-posh` and the `Paradox`, for example, already does this: (look at the thunder icon)
![image](https://user-images.githubusercontent.com/3901474/100496455-f09ed900-3132-11eb-82ec-d7936fbf89c3.png)

I've configured my terminal using these [steps from Scott Hansellman](https://www.hanselman.com/blog/how-to-make-a-pretty-prompt-in-windows-terminal-with-powerline-nerd-fonts-cascadia-code-wsl-and-ohmyposh). Special indicators for admin seem to be a pretty common feature of Pwsh themes.

**Comment by gerardog** [comment] 2020-12-20 22:23
I've been busy lately but finally got some time so I just released v0.7.3, where this shouldn't be an issue anymore.
The default prompt is `$p$e[1;31m# $e[0m` now. This should set the red pound and then restore the proper background and foreground color.

If you have changed this setting and want to revert to the new default use `gsudo config prompt --reset`
Thanks

**Closed by gerardog** 2020-12-20 22:23 UTC

**Comment by bearbattle** [comment] 2022-04-06 06:15
Hi There! I'm using Windows Terminal with default theme of PowerShell.

When I type sudo and elevated, `Space` and `BackSpace` would create black blank foregraound like stuffs in img.

![Black blanks](https://user-images.githubusercontent.com/48974238/161907200-2580a42e-0bce-4633-a42b-cbb2dd8e7df6.png)

After trying different `gsudo config prompt`, things does not change at all. Are there any workaround?

**Comment by gerardog** [comment] 2022-04-06 08:24
@bearbattle show me please the result of 'gsudo config" snd "gsudo -v", and windows version

**Comment by gerardog** [comment] 2022-04-07 02:35
@bearbattle Just realized you are using PowerShell and `gsudo config prompt` has no effect inside powershell. Im not sure this problem is related to gsudo. Just in case ensure you are using a recent version.

Also please let me know: Are you using Windows Terminal? could you please try to reproduce the issue on WT? If the problem does not ocurr there, this may be a problem with the Console window itself.
thanks

**Comment by bearbattle** [comment] 2022-04-07 06:29
Hi there @gerardog ! Previously I'm using Windows Terminal with Powershell when coming up with this issue. Currently even aftrer some theme related beautify work (`posh-git` and `oh-my-posh`), the issue seems remain the same.

BUT When using PowerShell's own Console, the problem is gone!

Windows Terminal Version: `1.11.3471.0`

gsudo version: `gsudo v1.2.0 (Branch.master.Sha.2e8cc8ac942dd01df05479412b526b13ba22c1bb)`

![Screenshot](https://user-images.githubusercontent.com/48974238/162133336-923a0b60-f54b-4476-b353-fe43008eaf83.png)

Reproduce step:

1. Open Windows Terminal with theme which is non-black bgcolor
2. Type `sudo` and enter to elevate the terminal session
3. Type space or use backspace would produce black blank in terminal

**Comment by gerardog** [comment] 2022-04-07 06:34
Could you share your WT theme please?

**Comment by bearbattle** [comment] 2022-04-07 06:36
```json
{
    "acrylicOpacity": 0.75,
    "antialiasingMode": "grayscale",
    "colorScheme": "Campbell Powershell",
    "commandline": "powershell.exe",
    "font": 
    {
        "face": "CaskaydiaCove NF"
    },
    "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
    "hidden": false,
    "name": "Windows PowerShell",
    "useAcrylic": true
}
```

**Comment by gerardog** [comment] 2022-04-07 06:44
Thanks. I cant reproduce the problem...

![image](https://user-images.githubusercontent.com/3901474/162136358-43412d58-b137-4cb5-a323-f56457cf1bb9.png)

Could you share your `Get-PSReadLineOption` results, and your `Oh-my-posh` lines from the `$PROFILE`?

**Comment by gerardog** [comment] 2022-04-07 06:47
Also... just to be sure... 
Could you open `pwsh` in the same way, and then call `pwsh` again (instead of gsudo) , and see if the problem ocurrs without gsudo?

**Comment by gerardog** [comment] 2022-04-07 06:54
I think I found the problem... Not rooted in gsudo, but gsudo triggers it by launching the 'dotnet global' version of pwsh...

See: https://github.com/PowerShell/PSReadLine/issues/1842

Can be fixed by updating PSReadLine module.  ('Update-Module PSReadLine'?)

We can confirm if you gsudo first, then run gsudo status, and both `pwsh.exe` paths differ: (mines are equal)
![image](https://user-images.githubusercontent.com/3901474/162138079-2e67ab78-c5ca-4d83-a66a-37cb49264c55.png)

**Comment by bearbattle** [comment] 2022-04-07 06:58
![Get-PSReadLineOption](https://user-images.githubusercontent.com/48974238/162137395-a4529d42-b7d6-4064-966a-65ceb7deb171.png)

I notice that you're using `PowerShell Core` but I'm using `PowerShell`.

![PSVersionTable](https://user-images.githubusercontent.com/48974238/162137779-633baf65-ecd7-46d3-98c4-bd920dfcc799.png)

Direct call `powershell` would not produce the issue. The issue seem to happen onlyafter I call `sudo` in WT.

![Direct Call](https://user-images.githubusercontent.com/48974238/162138679-bee02f56-f393-4b54-ae45-075f6167ac79.png)

**Comment by gerardog** [comment] 2022-04-07 07:08
now sudo, then Get-PSReadLineOption and lets see the differences...
Also, whats your psreadline version, have you updated it?

**Comment by bearbattle** [comment] 2022-04-07 07:13
![Difference](https://user-images.githubusercontent.com/48974238/162141266-e4a2891c-e019-4682-b3dd-52a7bacfe85b.png)

I have not update my PSReadline.

**Comment by gerardog** [comment] 2022-04-07 07:23
works for me.

![image](https://user-images.githubusercontent.com/3901474/162142658-ff509f82-5265-4ae7-97e1-32dfa694bbc0.png)
![image](https://user-images.githubusercontent.com/3901474/162142939-9b5e270e-2337-4ef2-bcfa-143b6280f19d.png)

paste your `gsudo status` please

**Comment by bearbattle** [comment] 2022-04-07 07:46
![image](https://user-images.githubusercontent.com/48974238/162147379-ca368e68-73af-49b4-95ce-dddb0958e7ed.png)

**Comment by bearbattle** [comment] 2022-04-07 07:57
> I think I found the problem... Not rooted in gsudo, but gsudo triggers it by launching the 'dotnet global' version of pwsh...
> 
> See: [PowerShell/PSReadLine#1842](https://github.com/PowerShell/PSReadLine/issues/1842)
> 
> Can be fixed by updating PSReadLine module. ('Update-Module PSReadLine'?)
> 
> We can confirm if you gsudo first, then run gsudo status, and both `pwsh.exe` paths differ: (mines are equal) ![image](https://user-images.githubusercontent.com/3901474/162138079-2e67ab78-c5ca-4d83-a66a-37cb49264c55.png)

Thanks. After upgrade my PSReadline to 2.2.2 and the problem resolved!
