### ISSUE TITLE
Issue: Nano and vim executables get stuck when opened with gsudo on cmd

### ISSUE THREAD

**Issue by AngelAGBL** [gerardog/gsudo#302] opened 2023-09-16 19:42 UTC
## Issue Description
When I try to execute nano or vim from msys2 (yes, these programs are added to my PATH) with privileges on cmd they get stuck, this doesn't happen on powershell:

## Steps to Reproduce

1. Open cmd
2. Execute ```gsudo nano``` or ```gsudo vim```

## Screenshots 

|Nano|Vim|
|-|-|
|![image](https://github.com/gerardog/gsudo/assets/106941728/5c2e1fcb-e46e-46fa-b63b-0f6c677c6a58)|![image](https://github.com/gerardog/gsudo/assets/106941728/dc015f5e-5aa0-419a-a814-b178da620295)|

This issue doesn't get solved using --direct mode, the only way to make this work is executing:
```gsudo cmd /c nano```
```gsudo cmd /c vim``` 
It would be useful to execute them directly with gsudo, so I'll thank you if you'll give it some solution

## Context:
  - Windows version: Win11 22H2 - Spanish
 
  - gsudo version: v2.4.0 or below

**Comment by gerardog** [comment] 2023-09-18 14:20
I don't know what is the root cause of the problem, but here is a workaround that will add the `cmd /c` automatically:

Please run:
```
gsudo config ExceptionList = "notepad.exe;powershell.exe;vim.exe;nano.exe;"
```

Thank you.

**Comment by gerardog** [comment] 2023-09-18 14:21
Please don't close the issue. I will after, at least, adding `vim` and `nano` by default in the exceptionlist.

**Comment by AngelAGBL** [comment] 2023-09-18 19:30
Ok, thanks a lot, that works

**Comment by gerardog** [comment] 2023-12-18 10:44
How have you installed vim and nano on windows? using a windows installer? using git-bash? 
Where are your `vim.exe` and `nano.exe` files located?
(on cmd, run `which vim`)

**Comment by AngelAGBL** [comment] 2023-12-18 20:31
They are both installed from the msys2 project (https://www.msys2.org/) and are located in the ```C:\msys64\usr\bin``` directory

**Closed** 2024-02-20 01:51 UTC
