### ISSUE TITLE
gsudo hangs when run from Windows Terminal started with wt alias

### ISSUE THREAD

**Issue by dafzor** [gerardog/gsudo#43] opened 2020-06-10 22:03 UTC
I'm trying out `gsudo` and from `cmd`, `pwsh` or Windows Terminal shortcut it works as expected.

However when starting Windows terminal by the `wt` alias `gsudo` will "hang" and never shows the elevation prompt.

Further details:
* Windows 10 2004
* Windows Terminal 1.0.1401.0 (Store version)
* gsudo 0.7 and 0.5 ?? [ https://ci.appveyor.com/project/gerardog/gsudo/builds/33404236/artifacts ]

![image](https://user-images.githubusercontent.com/1612206/84323101-1678f700-ab6e-11ea-8a85-74779d721c84.png)

**Comment by gerardog** [comment] 2020-06-10 23:23
> gsudo 0.5 ?? 

AppVeyor builds dont have the right version numbers, my bad. :(

> when starting Windows terminal by the wt alias

Could you please describe this "wt alias". What is it? How do you installed it? Is `wt` running as your current user? Not sure why that alias made a windows service launch gsudo.

Thanks for your capture of the thread call stack. Is really helpfull. Looks like it's on an infinite loop on [this function](https://github.com/gerardog/gsudo/blob/master/src/gsudo/Helpers/ProcessHelper.cs#L117). I will check further.

**Comment by dafzor** [comment] 2020-06-10 23:26
`wt` alias is a standard feature of Windows store apps.

You can check the ones on your system by typing "Manage app execution aliases" in the start menu to open the corresponding control panel:
![image](https://user-images.githubusercontent.com/1612206/84328540-2565a680-ab7a-11ea-974d-0180a22793b9.png)

**Comment by gerardog** [comment] 2020-06-11 02:08
I've replaced GetParentProcessId implementation to one based on the NtQueryInformationProcess Api. It does not loop thru the process list, so it shouldnt hang.
Nonetheless I wasn't able to reproduce the issue, so, could you please test this build for me? 

https://ci.appveyor.com/project/gerardog/gsudo/builds/33450338/artifacts

Thank you

**Comment by dafzor** [comment] 2020-06-11 02:12
The build you linked seems to work as expected. Thanks for the quick fix.
![image](https://user-images.githubusercontent.com/1612206/84337379-4d143900-ab91-11ea-878c-6a58f2555e88.png)

**Comment by gerardog** [comment] 2020-06-11 02:18
Great! 

This issue should auto-close when this is merged to master.

**Comment by dafzor** [comment] 2020-06-11 02:19
Out of curiosity did it really not behave the same on your system?

**Comment by gerardog** [comment] 2020-06-11 02:36
It did not. I tried running WT from the command line with MsStore aliases (`C:\Users\Me\AppData\Local\Microsoft\WindowsApps\wt.exe`) and still it was created with `explorer.exe` parent process. (not svchost/sihost).
I tried to force a hang in the older GetParentProcessId implementation (based on CreateToolhelp32Snapshot) but I couldn't either. 
(I wonder if you can still reproduce this after a reboot, which is a not a fix, but stil curious).

Anyway... I didn't liked much to iterate O(n) all processes to get one PPID. The new implementation just looks better to me. (IMHO, even if it is flagged as deprecated, NtDll.dll is not going away for another decade, because there is no better alternative).

**Comment by dafzor** [comment] 2020-06-11 02:47
Tried following the steps you described and saw the same behavior.

It seems it only happens with opening the start menu, typing `wt` and pressing enter. So I assume the service it starts under is the one responsible for running the Windows 10 start menu.

Video: https://streamable.com/al5xbv

**Comment by gerardog** [comment] 2020-06-12 03:41
The fix was released in [v0.7.1](https://github.com/gerardog/gsudo/releases/tag/v0.7.1).
Let me know if this or any other problem ocurrs.
Thanks for reporting the problem.

**Closed by gerardog** 2020-06-12 03:41 UTC
